name: WiderWorldBorder
version: '${project.version}'
main: net.kunmc.lab.widerworldborder.WiderWorldBorder
api-version: 1.16
authors: [ Yanaaaaa ]
description: Mobを倒すとワールドボーダーが広がるプラグイン
commands:
  wwb:
    description: WiderWorldBorder Plugin
    usage: コマンド一覧:/<command>
    permission: WWB
permissions:
  WWB:
    default: op
